name: Run Tests

on:
  push:
    branches:
      - main  # Or the branch you're working with
  pull_request:
    branches:
      - main  # Or the branch you're working with

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set Java version to 17
          distribution: 'temurin'  # Change to 'temurin' for Adoptium JDK

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test